//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityConstants {
    
    
    public sealed class Tags {
        
        public const string Untagged = "Untagged";
        
        public const string Respawn = "Respawn";
        
        public const string Finish = "Finish";
        
        public const string EditorOnly = "EditorOnly";
        
        public const string MainCamera = "MainCamera";
        
        public const string Player = "Player";
        
        public const string GameController = "GameController";
        
        public const string FxTemporaire = "FxTemporaire";
        
        private Tags() {
        }
    }
}
